server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  datasource:
    url: jdbc:mysql://123.207.182.40:3306/acgshelf?useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: lls0908329

mybatis:
  configuration:
    map-underscore-to-camel-case: true   #开启驼峰命名转换

jwt:
  token:
    secret: quding2017
