server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/acgshelf?useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: lls0908329
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10             #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      auto-commit: true
      idle-timeout: 600000              #一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      pool-name: DatebookHikariCP
      max-lifetime: 1800000             #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      connection-timeout: 30000         #等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connection-test-query: SELECT 1

mybatis:
  configuration:
    map-underscore-to-camel-case: true   #开启驼峰命名转换

jwt:
  token:
    secret: quding2017
